name: flutter_beacon
description: Flutter plugin for scanning and transmit as beacon (iBeacon) on Android and iOS.
version: 0.5.2
homepage: https://github.com/alann-maulana/flutter_beacon

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterbeacon
        pluginClass: FlutterBeaconPlugin
      ios:
        pluginClass: FlutterBeaconPlugin
